name: secret_seal_sauce
description: A website to engage the public on Monk Seal conservation

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  cloud_firestore: ^2.2.2
  equatable: ^2.0.3
  firebase_analytics: ^8.1.2
  firebase_core: ^1.3.0
  firebase_storage: ^8.1.3
  flutter:
    sdk: flutter
  flutter_bloc: ^7.0.1
  flutter_svg: ^0.22.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  lint: ^1.5.3
  test: ^1.17.9

flutter:
  uses-material-design: true
  assets:
    - assets/images/
