name: secret_seal_sauce
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  cloud_firestore: null
  equatable:
  firebase_analytics: null
  firebase_core: null
  firebase_storage: null
  flutter:
    sdk: flutter
  flutter_bloc:
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint:

flutter:
  uses-material-design: true
  assets:
    - assets/images/
