name: secret_seal_sauce
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  cloud_firestore: 
  equatable: 
  # firebase_analytics: not ready for NNBD
  firebase_core: 
  firebase_storage: 
  flutter:
    sdk: flutter
  flutter_bloc: 
  flutter_svg: ^0.21.0-nullsafety.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  lint:
  test:

flutter:
  uses-material-design: true
  assets:
    - assets/images/
