on:
  pull_request:
    branches:
      - dev
      - prod
  push:
    branches:
      - issue1
      - dev
      - prod

jobs:
  build:
    # builing for web doesn't require macOS
    runs-on: ubuntu-latest

    steps:
    # output the build number used in this job
    - name: Output Run Info
      run: echo "build-number=$GITHUB_RUN_NUMBER, event = ${{ github.event_name }}, branch = ${{ github.ref }}, target = ${{ github.base_ref }}"
    
    # several actions use checkout
    - name: Install checkout
      uses: actions/checkout@v2

    # the flutter-action action needs java
    - name: Install Java for Flutter tool
      uses: actions/setup-java@v1
      with:
        java-version: '12.x'

    # use flutter-action configured with flutter channel
    - name: Install Flutter tool
      uses: subosito/flutter-action@v1
      with:
        channel: dev

    # enable Flutter for web
    - run: flutter config --enable-web

    # get app dependencies
    - run: flutter pub get

    # run app tests
    - run: flutter test

    # produce a build for web
    - name: Build for web
      # if: github.base_ref == 'refs/heads/prod'
      run: flutter build web