name: Deploy to Firebase Hosting
'on':
  pull_request:
    branches:
      - dev
      - prod
jobs:
  build_and_preview:
    runs-on: ubuntu-latest
    steps:
    # output the build number used in this job
    - name: Output Run Info
      run: echo "build-number=$GITHUB_RUN_NUMBER, event = ${{ github.event_name }}, branch = ${{ github.ref }}, target = ${{ github.base_ref }}"
      
    # several actions use checkout
    - name: Install checkout
      uses: actions/checkout@v2

    # the flutter-action action needs java
    - name: Install Java for Flutter tool
      uses: actions/setup-java@v1
      with:
        java-version: '12.x'

    # use flutter-action configured with flutter channel
    - name: Install Flutter tool
      uses: subosito/flutter-action@v1
      with:
        channel: dev

    # enable Flutter for web
    - run: flutter config --enable-web

    # get app dependencies
    - run: flutter pub get

    # run app tests
    - run: flutter test

    # produce a build for web
    - name: Build for web
      run: flutter build web

    # run echo tests
    - name: Run echo tests
      run:
        # echo ${{ github.base_ref }}
        # echo ${{ github.ref }}
        # echo ${{ github.ref == 'refs/heads/dev' }}
        # echo ${{ github.ref == 'dev' }}
        # echo ${{ github.base_ref == 'refs/heads/dev' }}
        echo ${{ github.base_ref == 'prod' }}
        echo ${{ github.base_ref == 'dev' }}

    # send to Firebase preview channel
    - name: send to Firebase Hosting preview channel
      if: github.base_ref == 'dev'
      uses: FirebaseExtended/action-hosting-deploy@v0
      with:
        repoToken: '${{ secrets.GITHUB_TOKEN }}'
        firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_SECRET_SEAL_SAUCE }}'
        projectId: secret-seal-sauce
      env:
        FIREBASE_CLI_PREVIEWS: hostingchannels

    # send to Firebase Hosting live channel
    - name: send to Firebase Hosting live channel
      if: github.base_ref == 'prod'
      uses: FirebaseExtended/action-hosting-deploy@v0
      with:
        repoToken: '${{ secrets.GITHUB_TOKEN }}'
        firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_SECRET_SEAL_SAUCE }}'
        channelId: live
        projectId: secret-seal-sauce
      env:
        FIREBASE_CLI_PREVIEWS: hostingchannels